# Medical Examiner Case Archives

Cook County (Chicago) medical examiner records, taken from [here](https://datacatalog.cookcountyil.gov/Public-Safety/Medical-Examiner-Case-Archive/cjeq-bs86) after discovery via [Data is Plural](https://tinyletter.com/data-is-plural).

## Do your importing/setup

In [7]:
import pandas as pd
import numpy as np
%matplotlib inline

## Read in the data, check its row count and column types

In [17]:
df = pd.read_csv("case-archive-encoded.csv", na_values=['nan'])
df.head()

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,1,5,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,1,5,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,1,5,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,0,5,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,1,2,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"

In [5]:
df.shape

(22634, 20)

In [6]:
df.dtypes

Case Number              object
Date of Incident         object
Date of Death            object
Age                     float64
Gender                    int64
Race                      int64
Latino                     bool
Manner of Death          object
Primary Cause            object
Primary Cause Line B     object
Primary Cause Line C     object
Secondary Cause          object
Gun Related              object
Opioid Related           object
Incident Address         object
Incident City            object
longitude               float64
latitude                float64
OBJECTID                  int64
location                 object
dtype: object

## Cleaning up your data

First you'll want to convert the `Race` and `Gender` columns from codes into actual text to make analysis easier.

### Gender codes

* `-1` - `Data missing`
* `0` - `Female`
* `1` - `Male`
* `2` - `Unknown`

### Race codes

* `-1` - `Data missing`
* `0` - `American Indian`
* `1` - `Asian`
* `2` - `Black`
* `3` - `Other`
* `4` - `Unknown`
* `5` - `White`

In [18]:
df.Gender.replace({
    -1: "Data missing",
    0: "Female",
    1: "Male",
    2: "Unknown",
}, inplace=True)

In [24]:
df.Race.replace({
    -1: "Data missing",
    0: "American Indian",
    1: "Asian",
    2: "Black",
    3: "Other",
    4: "Unknown",
    5: "White",
}, inplace=True)

In [25]:
df.head()

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
0,ME2017-04255,09/10/2017 08:28:00 PM,09/10/2017 08:51:00 PM,51.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20468,NaN
1,ME2018-02149,05/05/2018 06:30:00 AM,05/05/2018 06:41:00 AM,65.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2110 W. 21ST PL #1,CHICAGO,-87.678845,41.853279,77827,"(41.8532787, -87.6788449)"
2,ME2018-02154,04/26/2018 08:29:00 AM,05/05/2018 04:45:00 AM,95.0,Male,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20704 S Woodlawn Ct,FRANKFORT,NaN,NaN,77839,NaN
3,ME2018-02156,05/05/2018 12:00:00 PM,05/05/2018 12:25:00 PM,64.0,Female,White,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"4008 W. BERTEAU AVENUE, APT #1",CHICAGO,-87.728177,41.957468,77823,"(41.9574677, -87.7281769)"
4,ME2018-02158,05/05/2018 09:30:00 AM,05/05/2018 09:50:00 AM,61.0,Male,Black,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3947 W. LEXINGTON STREET,CHICAGO,-87.724739,41.871451,77822,"(41.8714515, -87.7247386)"

## What percent of the dataset is men, and what percent is women?

It should display as **Male** and **Female**, not as numbers.

In [11]:
df['Gender'].value_counts()

Male            16158
Female           6363
Data missing      101
Unknown            12
Name: Gender, dtype: int64

In [13]:
df['Gender'].value_counts(normalize=True)*100

Male            71.388177
Female          28.112574
Data missing     0.446231
Unknown          0.053018
Name: Gender, dtype: float64

## Getting rid of "Data missing"

`Unknown` means that officially the gender or race is unknown, while `Data missing` means the record is incomplete. That means "Data missing" should have been `NaN`!

Go back to your `read_csv` many cells before and make it so that "Data missing" is automatically set as `NaN`.

- *Tip: Do not use `.replace` for this one!*
- *Tip: Look at the options for `read_csv`, there's something that lets you specify missing values*
- *Tip: It isn't `"Data missing"` - think about how you already replaced*
- *Tip: Be sure you're using an array when you tell it what the 'missing' options are*

### After you've done this, re-run all of the the previous cells and confirm that `"Data missing"` does not exist any more

## What is the most common race in the dataset? We want percentages.

We'll come back to this later, I'm just having you check the column for now.

In [29]:
df['Race'].value_counts(normalize=True)*100

White              55.182469
Black              41.380224
Asian               1.511001
Other               1.188478
Data missing        0.547848
Unknown             0.123708
American Indian     0.066272
Name: Race, dtype: float64

## Do a `.value_counts()` on the `Opioid Related` column

In [43]:
df["Opioid Related"].value_counts()

True    3378
Name: Opioid Related, dtype: int64

## That's weird. Did everyone die from opioids? Try again, but including missing data.

In [47]:
df["Opioid Related"].isnull().sum()

19256

## Cleaning up True/False columns

For some reason in this dataset, the True/False columns are either `True` or `NaN`. `NaN` causes a lot of problems, I'd rather have it be false.

You can use [`fillna`](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.fillna.html) to fill in empty data - it's like `.replace` but for `NaN`.

### Replace all `NaN` values with `False` for the "Gun Related" and "Opioid Related" columns.

In [61]:
df["Gun Related"].fillna(False, inplace=True)

In [60]:
df["Opioid Related"].fillna("False", inplace=True)

### Do another value counts on Opioid Related to make sure it has both True and False values

In [62]:
df["Opioid Related"].value_counts()

False    19256
True      3378
Name: Opioid Related, dtype: int64

# Back to analysis!

## What's the average age people were when they died?

In [63]:
df['Age'].mean()

51.279928793947484

## Let's look at how the oldest people died

We're just going to browse. Read through how the **oldest 30 people died.**

In [84]:
df.sort_values(by='Age', ascending=False).head(30)

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
21142,ME2018-00494,01/11/2018 12:00:00 PM,01/24/2018 03:48:00 PM,106.0,Female,White,False,ACCIDENT,COMPLICATIONS OF A FALL,NaN,NaN,NaN,False,False,627 ORIOLE DR SYMPHONY NURSING HOME,STREAMWOOD,-88.166639,42.014994,61564,"(42.0149937, -88.1666392)"
17602,ME2017-02853,06/19/2017 08:15:00 PM,06/20/2017 10:08:00 PM,106.0,Female,White,False,NaN,ACUTE MYOCARDIAL INFARCTION,NaN,NaN,"FRACTURE OF FEMUR DUE TO FALL, HYPERTENSIVE AN...",False,False,8021 W 151st St,ORLAND PARK,-87.815531,41.615936,59223,"(41.6159359, -87.8155315)"
12106,ME2016-03535,07/20/2016 06:30:00 PM,07/20/2016 06:58:00 PM,105.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,126 DIVERSEY,NORTHLAKE,-87.908596,41.929038,57807,"(41.9290381, -87.9085962)"
4942,ME2015-01809,04/26/2015 03:30:00 PM,05/03/2015 03:06:00 PM,103.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FALL,NaN,NaN,NaN,False,False,7 WILLOW COURT,COUNTRYSIDE,-87.860635,41.783044,56056,"(41.7830443, -87.8606347)"
9376,ME2016-00729,02/10/2016 11:53:00 PM,02/11/2016 12:25:00 AM,103.0,Female,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,1933 Arklow Street,SCHAUMBURG,-88.127944,42.025985,61674,"(42.0259851, -88.1279436)"
8653,ME2015-05648,12/28/2015 09:30:00 PM,12/28/2015 09:59:00 PM,103.0,Female,Black,False,NATURAL,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,NaN,NaN,NaN,False,False,"4206 W. POTOMAC, 1ST FLOOR",CHICAGO,-87.731690,41.904602,68911,"(41.904602, -87.7316903)"
14697,ME2016-06170,12/23/2016 10:30:00 PM,12/24/2016 02:00:00 AM,101.0,Female,Black,False,ACCIDENT,INHALATION OF PRODUCTS OF COMBUSTION,NaN,NaN,NaN,False,False,2000 S. 9TH,MAYWOOD,-87.843632,41.867806,62018,"(41.8678057, -87.8436321)"
11558,ME2016-02979,06/12/2016 08:30:00 AM,06/17/2016 07:50:00 AM,101.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMORAL NECK FRACTURE,NaN,NaN,"DEMENTIA, HYPERTENSION, ANEMIA",False,False,1270 FRANCISCAN DRIVE - MOTHER TERESA NH,LEMONT,-87.972860,41.679977,63499,"(41.6799768, -87.9728597)"
9904,ME2016-01281,03/13/2016 04:30:00 PM,03/13/2016 04:57:00 PM,101.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"3409 SOUTH ASHLAND, 1ST FLOOR REAR APT.",CHICAGO,-87.665314,41.831971,65188,"(41.831971, -87.6653139)"
13498,ME2016-04942,10/14/2016 04:00:00 PM,10/14/2016 04:21:00 PM,101.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"2626 NORTH LAKEVIEW, UNIT 3008",CHICAGO,-87.639827,41.930351,67009,"(41.9303508, -87.6398266)"
5621,ME2015-02517,06/17/2015 10:30:00 AM,06/17/2015 10:50:00 AM,101.0,Female,White,False,NATURAL,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,NaN,False,False,420 N. WOLF RD. #229,NORTHLAKE,-87.905080,41.915730,58002,"(41.9157304, -87.9050796)"
8656,ME2015-05651,12/30/2015 04:30:00 PM,12/30/2015 04:50:00 PM,101.0,Male,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,"733 W. 19TH STREET, GROUND APT",CHICAGO,-87.646042,41.856563,67437,"(41.8565629, -87.646042)"
8780,ME2016-00111,12/28/2015 11:11:00 PM,01/03/2016 11:40:00 AM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FRACTURE OF FEMUR,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,5333 N SHERIDAN RD #23J,CHICAGO,-87.654376,41.979434,74168,"(41.9794337, -87.6543755)"
5817,ME2015-02723,06/29/2015 11:00:00 AM,06/29/2015 11:46:00 AM,100.0,Male,White,False,NATURAL,ASCVD,NaN,NaN,NaN,False,False,1316 CONCORD LN,SCHAUMBURG,-88.112903,42.012324,62245,"(42.0123239, -88.1129032)"
4239,ME2015-01074,03/12/2015 10:00:00 AM,03/12/2015 04:30:00 PM,100.0,Female,White,False,ACCIDENT,FRACTURE OF HIP,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC R...",False,False,640 BERGANDY COURT,ELK GROVE VILLAGE,NaN,NaN,60570,NaN
7898,ME2015-04864,10/15/2015 07:41:00 PM,11/10/2015 10:30:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT HIP FRACTURE,NaN,NaN,"ATRIAL FIBRILLATION, DEMENTIA",False,False,336 S Windsor,ARLINGTON HEIGHTS,-87.964208,42.077622,60002,"(42.0776216, -87.9642079)"
14044,ME2016-05503,11/16/2016 09:55:00 AM,11/16/2016 10:00:00 AM,100.0,Male,Black,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,4900 W. POTOMAC 1ST FLR.,CHICAGO,-87.748635,41.904362,76597,"(41.904362, -87.7486353)"
13696,ME2016-05143,09/30/2016 12:00:00 PM,10/28/2016 04:08:00 AM,100.0,Female,Black,False,ACCIDENT,COMPLICATIONS OF BILATERAL FEMUR FRACTURES,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,Citadel NH 3701 W 183rd,HAZEL CREST,-87.706555,41.556419,63741,"(41.5564191, -87.7065553)"
798,ME2018-01708,04/08/2018 03:03:00 PM,04/08/2018 03:12:00 PM,100.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,4035 North Leclaire,CHICAGO,-87.754434,41.954423,73911,"(41.9544229, -87.7544336)"
10335,ME2016-01724,04/08/2016 06:00:00 AM,04/08/2016 06:47:00 AM,100.0,Male,White,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,2705 NORTH MOBILE,CHICAGO,-87.782931,41.929431,73899,"(41.9294315, -87.7829312)"
3985,ME2015-00812,02/19/2015 12:00:00 PM,02/25/2015 06:44:00 AM,100.0,Female,White,False,ACCIDENT,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,NaN,NaN,"FRACTURE OF RIGTH TIBIA, ALZHEIMER'S DISEASE,...",False,False,"Lexington Hospice, 815 E Irving Park Rd",STREAMWOOD,NaN,NaN,61176,NaN
9859,ME2016-01233,02/28/2016 10:25:00 AM,03/10/2016 03:20:00 AM,100.0,Female,Asian,False,ACCIDENT,SUBDURAL HEMORRHAGE,NaN,NaN,"ATRIAL FIBRILLATION, HYPERTENSIVE AND ATHEROSC...",False,False,1045 SOUTH GROVE AVENUE,OAK PARK,-87.795475,41.868916,63202,"(41.8689159, -87.7954748)"
17789,ME2017-03051,07/02/2017 03:45:00 PM,07/02/2017 05:40:00 PM,100.0,Female,White,False,ACCIDENT,ASPHYXIA,NaN,NaN,ORGANIC CARDIOVASCULAR DISEASE,False,False,"6840 N. SACRAMENTO AVENUE, ROOM# 414B",CHICAGO,NaN,NaN,75141,NaN
4015,ME2015-00842,02/16/2015 08:34:00 PM,02/26/2015 06:45:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS FOLLOWING LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,800 West Central Road,ARLINGTON HEIGHTS,-87.992553,42.068009,60130,"(42.0680087, -87.9925527)"
17142,ME2017-02376,05/24/2017 04:30:00 PM,05/24/2017 05:47:00 PM,100.0,Female,White,False,NATURAL,ORGANIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,WEST 36TH ST AND HERMITAGE AVE,CHICAGO,-87.669137,41.828642,64638,"(41.8286417, -87.6691374)"
2610,ME2014-01556,11/19/2014 10:41:00 AM,11/20/2014 08:35:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMORAL NECK FRACTURE,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,False,6631 N. Milwaukee,NILES,-87.791694,42.002101,77212,"(42.0021012, -87.7916938)"
5951,ME2015-02861,07/07/2015 12:15:00 PM,07/07/2015 12:36:00 PM,99.0,Male,Black,False,NATURAL,ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE,NaN,NaN,NaN,False,False,8915 SOUTH LAFLIN APT 404,CHICAGO,-87.660445,41.731752,64790,"(41.7317523, -87.6604447)"
2672,ME2014-01620,11/01/2014 04:26:00 AM,11/24/2014 05:09:00 PM,99.0,Female,White,False,ACCIDENT,COMPLICATIONS OF A FALL,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,False,2160 South 1st Avenue,MAYWOOD,-87.834769,41.861100,62445,"(41.8610998, -87.8347694)"
916,ME2015-01570,04/17/2015 08:00:00 AM,04/17/2015 08:38:00 AM,99.0,Female,White,False,ACCIDENT,CERVICAL INJURIES,NaN,NaN,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,CLARE OAKS ASSISTED LIVING,BARTLETT,NaN,NaN,60976,NaN
8670,ME2016-05013,10/18/2016 11:30:00 AM,10/19/2016 08:37:00 AM,99.0,Female,Black,False,NATURAL,INTRAPARENCHYMAL HEMORRHAGE OF THE PONS,NaN,NaN,NaN,False,False,14255 S CICERO RM 434,CRESTWOOD,-87.737508,41.633365,60491,"(41.6333655, -87.7375081)"

## Seems like a lot of problems with fractures

### What's the median age of someone dying from a cause that involves a fracture?

Are fractures especially dangerous for the elderly?

- *Tip: Filter for a cause that involves a fracture, then take the median age*
- *Tip: If you get a "cannot index NA values" error, the problem is it's trying to search `NaN` values and doesn't know what to do with them. You need to tell pandas to count `NaN` as false by setting another option - it isn't `NaN=False`, but it's close!*

In [154]:
df[df['Primary Cause'].str.contains('.*FRACTURE.*', na=False)]

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
173,ME2018-02232,05/10/2018 05:15:00 AM,05/10/2018 05:27:00 AM,98.0,Male,White,False,ACCIDENT,COMPLICATIONS OF FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,55 E. PEARSON ST.,CHICAGO,-87.626284,41.897293,78038,"(41.8972932, -87.6262844)"
325,ME2018-01200,02/27/2018 09:57:00 AM,03/07/2018 06:32:00 AM,86.0,Male,White,False,ACCIDENT,COMPLICATIONS OF FRACTURE OF HIP,NaN,NaN,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,4101 LAKE COOK RD,NORTHBROOK,-87.879300,42.151985,60909,"(42.1519851, -87.8792996)"
742,ME2018-01660,02/17/2018 12:00:00 AM,03/25/2018 07:05:00 AM,84.0,Female,White,False,ACCIDENT,LEFT FEMORAL NECK FRACTURE,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,2150 W. GOLF ROAD - ASSITED LIVING,HOFFMAN ESTATES,-88.132521,42.047745,60994,"(42.0477454, -88.1325211)"
886,ME2018-01684,03/30/2018 11:08:00 PM,04/06/2018 08:50:00 PM,85.0,Female,White,False,ACCIDENT,COMPLICATIONS OF PELVIS FRACTURES,NaN,NaN,"MALIGNANCY, ATRIAL FIBRILLATION, REMOTE CEREBR...",False,False,920 E. NORTHWEST HIGHWAY,PALATINE,-88.020844,42.101709,61503,"(42.101709, -88.0208439)"
911,ME2017-05372,11/15/2017 06:25:00 PM,11/15/2017 07:10:00 PM,84.0,Male,Asian,False,ACCIDENT,COMPLICATIONS OF RIGHT HIP FRACTURE,NaN,NaN,ALZHEIMER?S DISEASE AND ARTERIOSCLEROTIC CARDI...,False,False,504 W WELLINGTON ST,CHICAGO,-87.642031,41.936614,75882,"(41.936614, -87.6420313)"
951,ME2018-01756,04/05/2018 10:00:00 PM,04/11/2018 12:22:00 AM,92.0,Female,White,False,ACCIDENT,FRACTURE OF HIP,NaN,NaN,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,UNKNKOWN,NaN,NaN,NaN,55654,NaN
955,ME2018-01763,03/29/2018 12:00:00 AM,04/08/2018 07:20:00 AM,88.0,Female,White,False,ACCIDENT,RIGHT FEMUR NECK FRACTURE,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,480 N WOLF RD,NORTHLAKE,-87.904584,41.916897,72548,"(41.9168967, -87.9045839)"
1087,ME2018-01845,03/29/2018 08:00:00 AM,04/16/2018 01:45:00 AM,97.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND VALVULAR CARDIOVASCULAR DISEA...,False,False,"Sunrise NH, 1601 Green Bay Road",HIGHLAND PARK,NaN,NaN,57634,NaN
1128,ME2018-01879,01/30/2017 12:00:00 AM,01/31/2017 03:51:00 AM,93.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMUR FRACTURE,NaN,NaN,"CORONARY ARTERY DISEASE, CHRONIC OBSTRUCTIVE P...",False,False,701 W. North Avenue,MELROSE PARK,-87.842431,41.910330,61835,"(41.91033, -87.8424306)"
1241,ME2014-00114,08/03/2014 05:53:00 PM,08/16/2014 07:37:00 PM,94.0,Male,White,False,ACCIDENT,COMPLICATIONS OF HIP FRACTURE,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,401 w lake st,NORTHLAKE,-87.917790,41.905397,58345,"(41.9053973, -87.9177899)"
1369,ME2014-00248,08/22/2014 12:09:00 PM,08/27/2014 01:13:00 PM,94.0,Male,White,False,ACCIDENT,COMPLICATIONS OF HIP FRACTURE,NaN,NaN,"DIABETES MELLITUS, HYPERTENSIVE CARDIOVASCULAR...",False,False,NaN,NaN,NaN,NaN,56210,NaN
1491,ME2014-00375,09/02/2014 11:00:00 PM,09/04/2014 08:29:00 PM,82.0,Male,White,False,ACCIDENT,CLOSED HEAD INJURIES AND FACIAL FRACTURES,NaN,NaN,"ANTICOAGULANT THERAPY FOR ATRIAL FIBRILLATION,...",False,False,"820 WEIBNER STREET, UNIT 405",BUFFALO GROVE,-87.976136,42.140969,61314,"(42.1409692, -87.976136)"
1501,ME2014-00385,09/03/2014 12:30:00 PM,09/05/2014 02:54:00 PM,92.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,1301 Lee Street,DES PLAINES,-87.893280,42.029337,61585,"(42.0293371, -87.8932801)"
1664,ME2014-00554,09/11/2014 04:40:00 AM,09/16/2014 03:45:00 AM,84.0,Female,White,False,ACCIDENT,FRACTURE OF THE HIP,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,10505 S. Whipple,CHICAGO,-87.697423,41.702338,75830,"(41.7023382, -87.6974232)"
1731,ME2014-00622,09/05/2014 04:00:00 AM,09/21/2014 12:43:00 AM,75.0,Male,Other,False,ACCIDENT,COMPLICATIONS OF HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,1500 LAKE AVE,WILMETTE,-87.714653,42.079276,60627,"(42.0792756, -87.7146532)"
1732,ME2014-00623,09/19/2014 11:12:00 AM,09/21/2014 03:58:00 AM,80.0,Male,White,False,ACCIDENT,FRACTURE OF RIGHT HIP,NaN,NaN,CONGESTIVE HEART FAILURE,False,False,6141 N. Pulaski,CHICAGO,-87.728495,41.993094,77396,"(41.9930943, -87.7284954)"
1807,ME2014-00704,09/26/2014 10:00:00 AM,09/27/2014 06:52:00 AM,95.0,Female,White,False,ACCIDENT,LEFT HIP FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, DEMENTIA,...",False,False,3249 S. Oak Park Avenue,BERWYN,-87.792225,41.832622,57226,"(41.8326225, -87.7922251)"
1818,ME2014-00716,09/26/2014 11:08:00 PM,09/27/2014 12:14:00 AM,74.0,Male,White,False,ACCIDENT,BILATERAL PELVIC FRACTURES,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,17147 OAK PARK,TINLEY PARK,-87.784256,41.579209,59610,"(41.5792091, -87.7842559)"
2096,ME2014-01006,10/08/2014 12:00:00 AM,10/13/2014 04:45:00 PM,96.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,NaN,False,False,Emeritus Assisted Living 2150 West Golf Road,HOFFMAN ESTATES,-88.132521,42.047745,58135,"(42.0477454, -88.1325211)"
2121,ME2014-01033,10/16/2014 07:30:00 PM,10/18/2014 11:03:00 AM,91.0,Female,White,False,ACCIDENT,FRACTURE OF RIGHT HIP,NaN,NaN,DEMENTIA,False,False,1725 BALLARD ROAD,PARK RIDGE,-87.848510,42.042957,60234,"(42.0429573, -87.8485097)"
2403,ME2014-01339,10/29/2014 12:00:00 AM,11/06/2014 04:40:00 AM,91.0,Female,White,False,ACCIDENT,LEFT FEMUR FRACTURE,NaN,NaN,"DEMENTIA, HYPERTENSIVE AND ARTERIOSCLEROTIC CA...",False,False,615 Ridge,WILMETTE,-87.722938,42.076144,56335,"(42.0761442, -87.7229383)"
2434,ME2014-01371,11/08/2014 02:00:00 AM,11/08/2014 01:58:00 PM,93.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FEMORAL NECK FRACTURE,NaN,NaN,NaN,False,False,6120 W. Ogden,CICERO,-87.776573,41.832904,77460,"(41.8329043, -87.7765728)"
2499,ME2014-01442,11/12/2014 01:00:00 PM,11/13/2014 06:10:00 PM,88.0,Female,White,False,ACCIDENT,FRACTURE OF HIP,NaN,NaN,NaN,False,False,8915 OCTAVIA,MORTON GROVE,-87.808158,42.043275,61012,"(42.0432747, -87.8081576)"
2541,ME2014-01485,11/05/2014 02:33:00 PM,11/16/2014 01:40:00 PM,92.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMUR FRACTURE,NaN,NaN,NaN,False,False,811 E. Central Road #132,ARLINGTON HEIGHTS,-87.971780,42.064132,60266,"(42.0641324, -87.9717797)"
2566,ME2014-01511,10/22/2014 12:00:00 AM,11/16/2014 05:59:00 PM,85.0,Female,White,False,ACCIDENT,COMPLICATIONS OF A LEFT FEMUR FRACTURE,NaN,NaN,"STROKE (CEREBROVASCULAR), PEMPHIGOID",False,False,2437 N Meade,CHICAGO,-87.777879,41.924898,62093,"(41.9248976, -87.7778787)"
2587,ME2014-01533,11/19/2014 07:00:00 PM,11/19/2014 08:45:00 PM,92.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,1366 W. Fullerton/Imperial of Lincoln Park,CHICAGO,NaN,NaN,67010,NaN
2610,ME2014-01556,11/19/2014 10:41:00 AM,11/20/2014 08:35:00 PM,100.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMORAL NECK FRACTURE,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,False,6631 N. Milwaukee,NILES,-87.791694,42.002101,77212,"(42.0021012, -87.7916938)"
2706,ME2014-01656,11/12/2014 08:55:00 AM,11/27/2014 11:04:00 AM,93.0,Male,White,False,ACCIDENT,COMPLICATIONS OF PELVIC FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CONGESTIV...",False,False,816 ADAMS STREET APT C101,WESTMONT,NaN,NaN,64270,NaN
2758,ME2014-01710,11/13/2014 09:00:00 AM,11/14/2014 01:13:00 PM,90.0,Male,Black,False,ACCIDENT,COMPLICATIONS OF HIP FRACTURE,NaN,NaN,PRIOR MYOCARDIAL INFARCT,False,False,8925 SOUTH CONSTANCE,CHICAGO,-87.579020,41.732582,68071,"(41.7325821, -87.57902)"
2813,ME2014-01768,11/24/2014 03:00:00 PM,12/05/2014 11:15:00 PM,88.0,Male,White,False,ACCIDENT,LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,11025 Southwest Highway,PALOS HILLS,-87.808773,41.690899,59234,"(41.6908991, -87.8087728)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19529,ME2017-04829,10/01/2017 07:37:00 AM,10/12/2017 07:55:00 PM,89.0,Male,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,NaN,False,False,10820 183RD ST #9,ORLAND PARK,NaN,NaN,59351,NaN
19556,ME2017-04858,10/01/2017 12:00:00 PM,10/14/2017 11:52:00 PM,95.0,Female,White,False,ACCIDENT,COMPLICATIONS OF BILATERAL FEMUR FRACTURES,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,815 E Irving Park Rd (LEXINGTON OF STREAMWOOD...,STREAMWOOD,-88.162998,42.008961,70096,"(42.0089612, -88.162998)"
19736,ME2017-05047,09/28/2017 07:54:00 AM,10/27/2017 04:36:00 AM,72.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT HIP FRACTURE,NaN,NaN,"METASTATIC SMALL CELL LUNG CANCER, ORGANIC CAR...",False,False,2160 S. First Ave Loyola Campus Center,MAYWOOD,-87.834769,41.861100,62456,"(41.8610998, -87.8347694)"
19739,ME2017-05051,10/10/2017 12:00:00 AM,10/25/2017 07:14:00 PM,88.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,"HYPERTENSIVE AND VALVULAR HEART DISEASE, PULMO...",False,False,1750 Broadway,BLUE ISLAND,-87.663669,41.652054,57664,"(41.6520537, -87.6636693)"
19833,ME2017-05155,10/15/2017 12:00:00 PM,11/02/2017 05:38:00 AM,79.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,1030 N. State Street Apt 33E,CHICAGO,-87.628903,41.901593,66027,"(41.9015927, -87.6289028)"
20144,ME2017-05498,11/20/2017 12:00:00 PM,11/23/2017 02:20:00 PM,72.0,Female,Black,False,ACCIDENT,COMPLICATIONS OF FRACTURE OF HIP,NaN,NaN,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,12252 S. MICHIGAN,CHICAGO,-87.620532,41.671051,70741,"(41.6710508, -87.6205318)"
20157,ME2017-05515,11/16/2017 03:00:00 PM,11/24/2017 11:00:00 AM,91.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMUR FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CONGESTIV...",False,False,4924 N. Notingham,CHICAGO,-87.803946,41.970892,72148,"(41.9708919, -87.803946)"
20343,ME2017-05717,11/05/2017 12:00:00 AM,12/07/2017 12:00:00 PM,88.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE CARDIOVASCULAR DISEASE,False,False,7435 W. TALCOTT - RAINBOW HOSPICE,CHICAGO,-87.813102,41.987510,72348,"(41.98751, -87.8131025)"
20353,ME2017-05728,12/06/2017 09:00:00 PM,12/08/2017 07:13:00 AM,93.0,Female,White,False,ACCIDENT,LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND VALVULAR HEART DISEASE,False,False,"141 N. Lagrange Road, Apt. 604",LA GRANGE,-87.869653,41.819471,57612,"(41.8194706, -87.8696527)"
20504,ME2017-05895,12/13/2017 11:00:00 PM,12/17/2017 05:58:00 PM,90.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,False,407 ASHLAND AVE APT 4F,RIVER FOREST,-87.815697,41.887452,62948,"(41.8874519, -87.8156967)"
20514,ME2017-05905,12/12/2017 04:00:00 PM,12/18/2017 01:04:00 AM,87.0,Female,White,False,ACCIDENT,FRACTURE OF HIP,NaN,NaN,ORGANIC CARDIOVASCULAR DISEASE,False,False,6536 W. 91st Street,OAK LAWN,-87.783542,41.727075,59179,"(41.7270749, -87.7835422)"
20830,ME2018-00135,01/04/2018 03:22:00 AM,01/07/2018 05:10:00 AM,94.0,Male,Other,False,ACCIDENT,COMPLICATIONS OF FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,2380 John Smith Drive #E,SCHAUMBURG,-88.138304,42.042340,62363,"(42.04234, -88.138304)"
20864,ME2018-00171,01/08/2018 08:30:00 AM,01/08/2018 08:30:00 AM,94.0,Female,White,False,ACCIDENT,COMPLICATIONS OF PELVIC FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,800 W. OAKTON,ARLINGTON HEIGHTS,-87.992688,42.096586,56831,"(42.0965859, -87.9926879)"
20904,ME2018-00219,09/29/2017 09:47:00 AM,01/10/2018 06:10:00 AM,70.0,Male,White,False,ACCIDENT,COMPLICATIONS OF RIGHT HIP FRACTURE,NaN,NaN,"CANCER OF LUNG, ATHEROSCLEROTIC AND VALVULAR C...",False,False,17445 SAUK DRIVE,LOCKPORT,NaN,NaN,63734,NaN
20956,ME2018-00282,01/12/2018 09:35:00 PM,01/12/2018 09:50:00 PM,60.0,Male,White,True,ACCIDENT,PELVIC FRACTURES,NaN,NaN,"COCAINE AND ETHANOL TOXICITY, CHRONIC ETHANOLI...",False,False,3134 NORTH KEATING FL2,CHICAGO,-87.745883,41.938088,74072,"(41.9380881, -87.7458826)"
21016,ME2018-00353,01/18/2018 07:25:00 AM,01/18/2018 07:40:00 AM,67.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMUR FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC O...",False,False,3902 N. Mobile,CHICAGO,-87.783858,41.951374,72600,"(41.9513735, -87.7838583)"
21136,ME2018-00488,01/22/2018 12:30:00 PM,01/24/2018 08:10:00 AM,91.0,Female,White,False,ACCIDENT,PELVIC FRACTURES,NaN,NaN,NaN,False,False,1511 GREENWOOD RD. - GLENVIEW TERRACE NH,GLENVIEW,-87.838720,42.082265,61179,"(42.0822653, -87.8387203)"
21165,ME2018-00527,01/11/2018 12:00:00 PM,01/26/2018 04:56:00 PM,69.0,Male,White,False,ACCIDENT,COMPLICATIONS OF FIRST CERVICAL VERTEBRA FRACTURE,NaN,NaN,NaN,False,False,13324 W. CIRCLE DR. PARKWAY,CRESTWOOD,-87.745757,41.650121,62292,"(41.6501214, -87.7457571)"
21214,ME2018-00582,01/17/2018 07:30:00 PM,01/30/2018 02:24:00 PM,89.0,Female,White,False,ACCIDENT,COMPLICATIONS OF FEMUR FRACTURE,NaN,NaN,"INTESTINAL OBSTRUCTION, HYPERTENSIVE AND ARTER...",False,False,Brookdale NH 1515 Barrington Road,HOFFMAN ESTATES,-88.143203,42.050720,58101,"(42.0507204, -88.1432035)"
21245,ME2018-00619,01/01/2018 12:00:00 AM,02/02/2018 12:00:00 AM,76.0,Male,White,False,ACCIDENT,COMPLICATIONS OF FRACTURE OF HIP,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, DIABETES ...",False,False,1107 FULTON DR.,STREAMWOOD,-88.188002,42.010256,58192,"(42.0102559, -88.1880025)"
21338,ME2018-00721,02/08/2018 09:00:00 AM,02/08/2018 09:00:00 AM,96.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIGHT FEMUR FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, CHRONIC K...",False,False,800 W. CENTRAL,ARLINGTON HEIGHTS,-87.992553,42.068009,57255,"(42.0680087, -87.9925527)"
21342,ME2018-00725,02/04/2018 05:00:00 AM,02/08/2018 02:53:00 PM,79.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMUR FRACTURE,NaN,NaN,"HYPERTENSIVE CARDIOVASCULAR DISEASE, DIABETES ...",False,False,"333 NEWPORT LANE, UNIT #B1",BARTLETT,-88.168035,41.989491,57630,"(41.9894912, -88.1680351)"
21597,ME2018-01075,02/17/2018 02:43:00 AM,02/27/2018 05:01:00 PM,55.0,Female,White,False,ACCIDENT,COMPLICATIONS OF RIB FRACTURES,NaN,NaN,CHRONIC ETHANOLISM AND OBESITY,False,False,6734 West Forest Preserve Drive,HARWOOD HEIGHTS,-87.795552,41.959547,71671,"(41.9595468, -87.7955525)"
21699,ME2018-01216,03/04/2018 01:00:00 PM,03/07/2018 06:18:00 PM,87.0,Female,White,False,ACCIDENT,COMPLICATIONS OF LEFT FEMUR FRACTURE,NaN,NaN,"OSTEOPOROSIS, DEMENTIA, REMOTE CEREBROVASCULAR...",False,False,10 NORTH SUMMIT AVENUE,PARK RIDGE,-87.832052,42.011567,59772,"(42.0115666, -87.8320516)"
21714,ME2018-01226,01/30/2018 12:00:00 AM,03/08/2018 08:20:00 AM,81.0,Male,White,False,ACCIDENT,RIGHT FEMUR FRACTURE,NaN,NaN,HYPERTENSIVE ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,3555 N Neva,CHICAGO,-87.805572,41.945091,57107,"(41.9450905, -87.8055721)"
21805,ME2018-01330,03/01/2018 01:30:00 PM,03/13/2018 02:20:00 PM,79.0,Male,White,False,ACCIDENT,COMPLICATIONS OF RIGHT HUMERUS AND RIGHT FEMUR...,NaN,NaN,"ATHEROSCLEROTIC CARDIOVASCULAR DISEASE, TYPE 2...",False,False,10628 S WHIPPLE,CHICAGO,-87.697852,41.699864,76576,"(41.6998638, -87.6978521)"
22113,ME2015-04791,11/01/2015 06:06:00 PM,11/03/2015 04:00:00 PM,89.0,Female,White,False,ACCIDENT,FRACTURE OF RIGHT HUMERUS,NaN,NaN,"HYPERTENSIVE, ARTERIOSCLEROTIC AND VALVULAR CA...",False,False,6460 W. BELLENPLAINE AVENUE APT 406,CHICAGO,NaN,NaN,72325,NaN
22345,ME2017-03689,08/09/2017 10:00:00 AM,08/09/2017 12:00:00 AM,69.0,Female,White,False,ACCIDENT,COMPLICATIONS OF HIP FRACTURE,NaN,NaN,HYPERTENSIVE-ARTERIOSCLEROTIC CARDIOVASCULAR D...,False,False,2709 Scott St.,FRANKLIN PARK,-87.874594,41.927886,61754,"(41.9278857, -87.8745943)"
22429,ME2018-00217,12/21/2017 09:30:00 AM,01/09/2018 10:55:00 PM,79.0,Male,White,False,ACCIDENT,COMPLICATIONS OF LEFT HIP FRACTURE,NaN,NaN,HYPERTENSIVE AND ARTERIOSCLEROTIC CARDIOVASCUL...,False,False,800 S. RIVER ROAD,DES PLAINES,NaN,NaN,60492,NaN
22491,ME2018-01116,02/18/2018 12:00:00 AM,03/02/2018 06:30:00 AM,95.0,Female,White,False,ACCIDENT,RIGHT HIP FRACTURE,NaN,NaN,"ATRIAL FILBRILLATION, HYPERTENSIVE ARTERIOSCLE...",False,False,814 CATINO STREET,NaN,-87.993382,42.073178,55748,"(42.0731784, -87.9933821)"

In [160]:
df[df['Primary Cause'].str.contains('.*FRACTURE.*', na=False)].median()

/Users/linleysanders/.pyenv/versions/3.6.4/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1018: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Age               86.000000
Latino             0.000000
Gun Related        0.000000
longitude        -87.800225
latitude          41.924898
OBJECTID       60827.500000
dtype: float64

### To get a "compared to what?", what's the median age of _anyone_ dying an accidental death?

In [161]:
df[df['Manner of Death'].str.contains('.*ACCIDENT.*', na=False)].median()

Age               51.000000
Latino             0.000000
Gun Related        0.000000
longitude        -87.715975
latitude          41.871021
OBJECTID       65552.000000
dtype: float64

### What's the median age of each manner of death?

It looks like different kinds of death might happen to different ages of people. Let's investigate that further.

In [186]:
df.groupby('Manner of Death').median()

                  Age  Latino  Gun Related  longitude   latitude  OBJECTID
Manner of Death
ACCIDENT         51.0   False        False -87.715975  41.871021   65552.0
HOMICIDE         26.0   False         True -87.671368  41.801264   68575.0
NATURAL          61.0   False        False -87.695988  41.858385   67794.5
PENDING          47.0   False        False -87.700526  41.872046   73233.0
SUICIDE          45.0   False        False -87.728066  41.892251   64436.0
UNDETERMINED     21.0   False        False -87.668958  41.841308   66356.0

### Who is the oldest homicide victim?

It looks like homicide is for young people, so maybe we'll find an interesting outlier?

In [189]:
df.groupby('Manner of Death').max()

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Gun Related,longitude,latitude,OBJECTID
Manner of Death,,,,,,,,,,,
ACCIDENT,ME2018-02559,12/31/2017 12:50:00 PM,12/31/2017 12:54:00 PM,106.0,Male,White,True,True,-87.526669,42.154071,78959
HOMICIDE,ME2018-02571,12/31/2016 03:18:00 AM,12/31/2016 03:30:00 AM,98.0,Male,White,True,True,-87.526581,42.129071,78958
NATURAL,ME2018-02583,12/31/2017 12:00:00 PM,12/31/2017 12:58:00 PM,105.0,Male,White,True,False,-87.524835,42.153461,78949
PENDING,ME2018-02582,12/31/2017 11:23:00 PM,12/17/2017 04:57:00 AM,93.0,Male,White,True,False,-87.536788,42.147422,78955
SUICIDE,ME2018-02545,12/31/2017 08:17:00 PM,12/31/2017 09:14:00 PM,96.0,Male,White,True,True,-87.527878,42.151736,78930
UNDETERMINED,ME2018-02043,12/31/2016 12:25:00 PM,12/31/2016 12:51:00 PM,97.0,Unknown,White,True,True,-87.527615,42.150587,78862

## Investigating toxicity-related homicides

She was old, and was purposefully overdosed on morphine and hydrocodone. Might have been euthenasia? Let's find similar cases.

### Find every homicide where the primary cause of death is some sort of toxicity

Toxicity can just overdose. You should have **ten rows**.

- *Tip: If you're doing this as one statement, make sure you use your parentheses correctly. If you leave them out, you'll have zero rows*
- *Tip: You could make a homicides-only dataframe if you wanted to*

In [215]:
homicide = df[df['Manner of Death'].str.contains('HOMICIDE', na=False)]
homicide

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
14,ME2018-01126,03/03/2018 01:15:00 AM,03/03/2018 02:16:00 AM,37.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,159TH AND FINCH,HARVEY,-87.640104,41.600898,58723,"(41.6008977, -87.6401039)"
16,ME2018-01128,03/03/2018 02:51:00 AM,03/03/2018 03:13:00 AM,31.0,Male,Black,False,HOMICIDE,MULTIPLE SHARP FORCE INJURIES,NaN,NaN,NaN,False,False,6916 S. MICHIGAN AVENUE,CHICAGO,-87.622115,41.768692,77583,"(41.7686918, -87.6221153)"
19,ME2018-02093,05/01/2018 11:00:00 PM,05/01/2018 10:22:00 PM,31.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,4811 W. WASHINGTON BLVD.,CHICAGO,-87.745651,41.881767,77825,"(41.8817674, -87.7456512)"
20,ME2018-02096,05/02/2018 02:58:00 AM,05/02/2018 03:41:00 AM,69.0,Male,White,False,HOMICIDE,MULTIPLE STAB AND INCISED WOUNDS,NaN,NaN,NaN,False,False,5300 S. SOUTH SHORE DRIVE UNIT 43,CHICAGO,NaN,NaN,77978,NaN
22,ME2018-02095,05/01/2018 11:00:00 PM,05/01/2018 11:59:00 PM,37.0,Male,Black,False,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,False,False,1440 EMBASSY LANE,FORD HEIGHTS,-87.585216,41.513330,78840,"(41.5133297, -87.5852155)"
35,ME2018-02173,05/06/2018 09:07:00 PM,05/06/2018 09:41:00 PM,32.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,2451 EAST 78TH,CHICAGO,-87.564335,41.753452,78019,"(41.7534517, -87.5643355)"
37,ME2018-02176,05/06/2018 11:20:00 PM,05/07/2018 11:56:00 PM,36.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,3141 W . Madison,CHICAGO,-87.704685,41.880702,78045,"(41.8807021, -87.704685)"
38,ME2018-02168,05/05/2018 05:54:00 PM,05/06/2018 09:15:00 AM,11.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,False,3750 ELM STREET,EAST CHICAGO,NaN,NaN,78163,NaN
50,ME2017-04586,09/28/2017 12:09:00 PM,09/28/2017 12:50:00 PM,22.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,8139 SOUTH ELLIS AVENUE,CHICAGO,-87.599891,41.746527,77877,"(41.7465273, -87.599891)"
58,ME2018-02187,05/05/2018 03:09:00 PM,05/07/2018 12:19:00 PM,25.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,3731 West Roosevelt Road,CHICAGO,-87.719153,41.865896,78049,"(41.8658964, -87.7191531)"
63,ME2018-00820,02/13/2018 04:38:00 PM,02/13/2018 04:55:00 PM,24.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,469 Hirsch Avenue,CHICAGO HEIGHTS,NaN,NaN,57056,NaN
67,ME2018-00729,02/08/2018 08:43:00 PM,02/08/2018 08:52:00 PM,17.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,605 NORTH LARAMIE AVENUE,CHICAGO,-87.755222,41.891550,77905,"(41.8915496, -87.7552218)"
76,ME2018-02162,05/06/2018 12:00:00 AM,05/06/2018 05:16:00 AM,46.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF TORSO,NaN,NaN,NaN,True,False,8733 S. HALSTED ST.,CHICAGO,-87.643230,41.734927,78187,"(41.7349274, -87.6432303)"
79,ME2018-02171,04/22/2018 03:00:00 AM,05/06/2018 05:35:00 PM,24.0,Male,White,True,HOMICIDE,COMPLICATIONS OF STAB WOUND OF HEAD,NaN,NaN,NaN,False,False,559 E. MERLE LANE,WHEELING,-87.932089,42.129071,78535,"(42.1290714, -87.9320892)"
85,ME2017-01900,04/26/2017 01:36:00 AM,04/26/2017 02:04:00 AM,53.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,Oak Street at 14th Avenue,MAYWOOD,-87.850344,41.885991,62590,"(41.8859914, -87.850344)"
92,ME2018-01558,03/29/2018 04:10:00 PM,03/29/2018 04:42:00 PM,20.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,4005 W. VAN BUREN STREET,CHICAGO,-87.725657,41.875219,70515,"(41.8752193, -87.725657)"
110,ME2018-01984,04/25/2018 07:08:00 PM,04/25/2018 07:45:00 PM,51.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,7448 SOUTH PHILLIPS,CHICAGO,-87.564849,41.759407,77953,"(41.7594068, -87.5648491)"
118,ME2018-02113,05/02/2018 09:45:00 PM,05/03/2018 03:56:00 AM,21.0,Female,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,3510 W. Grenshaw,CHICAGO,-87.713463,41.867333,77954,"(41.867333, -87.713463)"
130,ME2018-02145,05/04/2018 09:35:00 PM,05/04/2018 11:55:00 PM,39.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,11732 SOUTH NORMAL,CHICAGO,-87.635017,41.680537,77924,"(41.680537, -87.6350168)"
140,ME2018-02191,05/07/2018 04:40:00 PM,05/07/2018 05:10:00 PM,30.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,3227 West Walnut,CHICAGO,-87.707403,41.885142,78073,"(41.8851419, -87.7074027)"
142,ME2018-02243,05/10/2018 02:22:00 PM,05/11/2018 06:21:00 AM,17.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF THE ABDOMEN,NaN,NaN,NaN,True,False,3301 W GLADYS,CHICAGO,-87.708451,41.876173,78259,"(41.876173, -87.7084507)"
150,ME2018-02161,05/06/2018 03:30:00 AM,05/06/2018 03:34:00 AM,26.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,2215 S. HOYNE AVENUE,CHICAGO,-87.678085,41.851474,78757,"(41.8514744, -87.6780849)"
156,ME2017-05365,11/10/2017 12:30:00 PM,11/15/2017 03:31:00 PM,2.0,Male,Black,False,HOMICIDE,BLUNT FORCE HEAD TRAUMA,NaN,NaN,NaN,False,False,832 RIDGE DRIVE APT #222,DEKALB,NaN,NaN,77996,NaN
157,ME2018-02034,04/29/2018 07:33:00 AM,04/29/2018 08:06:00 AM,23.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF CHEST,NaN,NaN,NaN,True,False,4757 W. Madison,CHICAGO,-87.744223,41.880463,78004,"(41.8804625, -87.7442229)"
160,ME2018-02214,05/08/2018 08:45:00 PM,05/08/2018 12:00:00 AM,53.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,6117 S RACINE REAR PROCH,CHICAGO,-87.654518,41.782921,78111,"(41.7829207, -87.6545184)"
163,ME2018-02204,05/08/2018 01:58:00 PM,05/08/2018 03:41:00 PM,24.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,6644 SOUTH JUSTINE STREET,CHICAGO,-87.663088,41.772727,78122,"(41.7727274, -87.6630883)"
172,ME2018-02211,05/08/2018 08:33:00 PM,05/08/2018 09:21:00 PM,15.0,Female,Black,False,HOMICIDE,GUNSHOT WOUND OF THE CHEST,NaN,NaN,NaN,True,False,6950 S. CARPENTER,CHICAGO,-87.650820,41.767257,78065,"(41.7672568, -87.65082)"
176,ME2018-02200,05/04/2018 03:25:00 PM,05/08/2018 10:15:00 AM,25.0,Male,Black,False,HOMICIDE,COMPLICATIONS OF MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,15516 Drexel Ave,DOLTON,-87.595584,41.612846,78058,"(41.6128458, -87.5955836)"
185,ME2018-02216,05/08/2018 09:34:00 PM,05/08/2018 10:02:00 PM,18.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,2215 S. Kildare,CHICAGO,-87.730982,41.850859,78211,"(41.8508594, -87.730982)"
194,ME2018-00689,02/06/2018 04:25:00 AM,02/06/2018 05:08:00 AM,23.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,14805 Maplewood,HARVEY,-87.678782,41.620536,78061,"(41.6205363, -87.678782)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22356,ME2017-04475,09/22/2017 08:19:00 PM,09/22/2017 08:36:00 PM,28.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,13340 SOUTH TORRENCE AVENUE,CHICAGO,-87.559377,41.653190,72408,"(41.6531902, -87.5593766)"
22361,ME2017-04593,06/28/2017 12:00:00 AM,09/29/2017 01:25:00 AM,23.0,Male,Black,False,HOMICIDE,COMPLICATIONS OF BLUNT FORCE HEAD TRAUMA,NaN,NaN,NaN,False,False,10200 S. STATE,CHICAGO,-87.623883,41.708852,70026,"(41.7088519, -87.6238829)"
22372,ME2017-04864,10/15/2017 11:10:00 AM,10/15/2017 11:38:00 AM,22.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,6741 S JEFFERY,CHICAGO,-87.576191,41.772227,75515,"(41.7722272, -87.5761914)"
22381,ME2017-05244,11/08/2017 02:30:00 AM,11/08/2017 03:40:00 AM,30.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,8158 S. COLFAX ST.,CHICAGO,-87.561385,41.747103,75806,"(41.7471026, -87.5613849)"
22391,ME2017-05499,11/23/2017 07:40:00 PM,11/23/2017 08:31:00 PM,18.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF CHEST,NaN,NaN,NaN,True,False,SAUK TRAIL AND ORHARD AVENUE,PARK FOREST,-87.681834,41.475907,59442,"(41.4759075, -87.6818341)"
22410,ME2017-05906,12/18/2017 09:13:00 AM,12/18/2017 09:42:00 AM,26.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF THE BACK,NaN,NaN,NaN,True,False,1624 SOUTH ST LOUIS AVE,CHICAGO,-87.713039,41.858267,70063,"(41.8582672, -87.7130387)"
22414,ME2017-06010,12/25/2017 12:15:00 AM,12/25/2017 12:28:00 AM,57.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,8137 S. WABASH,CHICAGO,-87.622523,41.746286,68502,"(41.7462864, -87.6225234)"
22420,ME2018-00010,01/01/2018 11:10:00 AM,01/01/2018 11:33:00 AM,29.0,Female,White,True,HOMICIDE,MULTIPLE INJURIES,NaN,NaN,NaN,False,False,2619 N. HAMPDEN COURT,CHICAGO,-87.640743,41.929862,67379,"(41.9298621, -87.6407427)"
22439,ME2018-00395,01/19/2018 06:38:00 PM,01/20/2018 12:04:00 AM,31.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF HEAD,NaN,NaN,NaN,True,False,2900 E 79TH ST,CHICAGO,-87.553862,41.752083,66046,"(41.7520825, -87.5538623)"
22450,ME2018-00535,01/27/2018 11:15:00 AM,01/27/2018 11:55:00 AM,20.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,1355 W. 110TH PLACE,CHICAGO,-87.655909,41.693060,57181,"(41.6930602, -87.6559086)"
22453,ME2018-00588,01/30/2018 09:51:00 PM,01/30/2018 10:01:00 PM,43.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,2424 WEST EASTWOOD,CHICAGO,-87.689864,41.965916,69956,"(41.965916, -87.6898635)"
22454,ME2018-00592,01/31/2018 01:36:00 PM,01/31/2018 02:02:00 PM,20.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,11114 SOUTH EMERALD AVENUE,CHICAGO,-87.641452,41.691896,71450,"(41.6918963, -87.6414523)"
22467,ME2018-00860,02/16/2018 08:13:00 PM,02/16/2018 11:58:00 PM,19.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,10248 S. HOXIE,CHICAGO,-87.561175,41.708513,59065,"(41.7085134, -87.5611751)"
22488,ME2017-04353,09/15/2017 08:35:00 PM,09/15/2017 10:19:00 PM,27.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,4701 SOUTH FAIRFIELD AVENUE,CHICAGO,-87.692914,41.808299,72427,"(41.8082987, -87.6929137)"
22489,ME2017-04354,09/15/2017 08:35:00 PM,09/15/2017 10:20:00 PM,21.0,Male,White,True,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,4701 SOUTH FAIRFIELD AVENUE,CHICAGO,-87.692914,41.808299,71991,"(41.8082987, -87.6929137)"
22492,ME2018-01117,03/02/2018 10:47:00 AM,03/02/2018 12:02:00 PM,14.0,Male,White,True,HOMICIDE,GUNSHOT WOUND OF ABDOMEN,NaN,NaN,NaN,True,False,3510 S Ashland,CHICAGO,-87.665914,41.830207,66151,"(41.8302068, -87.6659138)"
22513,ME2018-01957,04/23/2018 06:23:00 PM,04/23/2018 06:59:00 PM,23.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,209 NORTH LOCKWOOD,CHICAGO,-87.757363,41.884692,74961,"(41.8846922, -87.7573634)"
22517,ME2018-01970,04/24/2018 07:17:00 PM,04/24/2018 08:07:00 PM,21.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,12039 S. STEWART AVE,CHICAGO,-87.631820,41.674941,59356,"(41.6749411, -87.6318201)"
22528,ME2018-01987,04/25/2018 07:20:00 PM,04/25/2018 07:40:00 PM,20.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF THE CHEST,NaN,NaN,NaN,True,False,2915 S.Shields,CHICAGO,-87.635126,41.840601,66795,"(41.8406008, -87.6351261)"
22534,ME2018-01998,04/26/2018 05:17:00 PM,04/26/2018 05:50:00 PM,21.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF THE HEAD,NaN,NaN,NaN,True,False,1500 NORTH WASHTENAW,CHICAGO,-87.694579,41.908460,69428,"(41.9084604, -87.6945792)"
22538,ME2018-02005,04/27/2018 12:49:00 AM,04/27/2018 01:24:00 AM,23.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,130 ALGONQUIN,PARK FOREST,-87.670633,41.494301,57143,"(41.4943007, -87.6706335)"
22539,ME2018-02006,04/27/2018 02:36:00 AM,04/27/2018 03:02:00 AM,39.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF THE ABDOMEN,NaN,NaN,NaN,True,False,620 W. 63RD STREET,CHICAGO,-87.640472,41.780417,69300,"(41.7804171, -87.6404723)"
22548,ME2018-01986,04/25/2018 09:26:00 PM,04/25/2018 10:10:00 PM,28.0,Female,White,True,HOMICIDE,STAB WOUND OF CHEST,NaN,NaN,NaN,False,False,5959 S. SACRAMENTO,CHICAGO,-87.698186,41.784634,78109,"(41.7846339, -87.6981862)"
22550,ME2018-02015,04/27/2018 04:20:00 PM,04/27/2018 05:04:00 PM,39.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,8311 SOUTH MARSHFIELD,CHICAGO,-87.664284,41.742694,68907,"(41.7426943, -87.6642838)"
22562,ME2018-02044,04/29/2018 02:25:00 PM,04/29/2018 05:35:00 PM,29.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND TO THE HEAD,NaN,NaN,NaN,True,False,3 LONGWOOD PLACE,ELGIN,NaN,NaN,77787,NaN
22567,ME2018-02055,04/30/2018 08:56:00 AM,04/30/2018 09:22:00 AM,27.0,Male,Black,False,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,False,False,311 Boston Street,CHICAGO HEIGHTS,-87.657406,41.498638,56631,"(41.4986385, -87.6574062)"
22571,ME2018-02060,04/30/2018 01:57:00 PM,04/30/2018 02:00:00 PM,29.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,1300 S. Throop Avenue,CHICAGO,-87.658901,41.865183,67420,"(41.8651826, -87.6589013)"
22582,ME2018-01591,05/01/2018 01:10:00 AM,04/01/2018 01:34:00 AM,25.0,Male,Black,False,HOMICIDE,MULTIPLE GUNSHOT WOUNDS,NaN,NaN,NaN,True,False,715 E. 92ND PL,CHICAGO,-87.606356,41.726400,67846,"(41.7264005, -87.6063559)"
22610,ME2018-02098,05/02/2018 06:00:00 AM,05/02/2018 06:39:00 AM,56.0,Male,Black,False,HOMICIDE,MULTIPLE BLUNT FORCE INJURIES,NaN,NaN,NaN,False,False,216 w. 147TH STREET,HARVEY,-87.668955,41.622493,78086,"(41.6224931, -87.6689548)"
22628,ME2018-02123,05/03/2018 01:15:00 PM,05/03/2018 01:51:00 PM,42.0,Male,Black,False,HOMICIDE,GUNSHOT WOUND OF RIGHT BUTTOCK,NaN,NaN,NaN,True,False,8159 SOUTH CORNELL AVENUE,CHICAGO,-87.583910,41.746488,78103,"(41.7464877, -87.5839097)"

In [220]:
homicide[homicide['Primary Cause'].str.contains('.*TOXICITY.*', na=False)]

,Case Number,Date of Incident,Date of Death,Age,Gender,Race,Latino,Manner of Death,Primary Cause,Primary Cause Line B,Primary Cause Line C,Secondary Cause,Gun Related,Opioid Related,Incident Address,Incident City,longitude,latitude,OBJECTID,location
3702,ME2015-00519,02/03/2015 08:21:00 AM,02/04/2015 08:34:00 AM,98.0,Female,Black,False,HOMICIDE,MORPHINE AND HYDROCODONE TOXICITY,NaN,NaN,HYPERTENSIVE AND ATHEROSCLEROTIC CARDIOVASCULA...,False,True,16300 louis Ave,SOUTH HOLLAND,-87.609278,41.598109,64404,"(41.5981086, -87.6092784)"
5395,ME2015-02286,05/27/2015 03:15:00 PM,06/03/2015 07:25:00 PM,28.0,Female,White,False,HOMICIDE,"COMPLICATIONS OF AMITRIPTYLINE AND METABOLITE,...",NaN,NaN,NaN,False,False,1102 S. Springinsguth Rd. #1D,SCHAUMBURG,-88.119741,42.005376,60663,"(42.005376, -88.1197414)"
6144,ME2015-03058,07/18/2015 07:00:00 AM,07/19/2015 02:05:00 AM,10.0,Male,Black,False,HOMICIDE,CARBON MONOXIDE TOXICITY,INCENDIARY HOUSE FIRE,NaN,NaN,False,False,8327 S. DREXEL,CHICAGO,-87.602328,41.743167,68218,"(41.7431675, -87.6023283)"
6764,ME2015-03692,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,28.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,NaN,False,False,5209 S Lorel Avenue,CHICAGO,-87.755913,41.798035,72663,"(41.7980351, -87.7559129)"
6765,ME2015-03693,08/29/2015 09:41:00 AM,08/29/2015 01:00:00 PM,63.0,Male,Other,False,HOMICIDE,CARBON MONOXIDE TOXICITY,HOUSE FIRE,NaN,"ARTERIOSCLEROTIC CARDIOVASCULAR DISEASE, ACUTE...",False,False,5205 S. Lorel,CHICAGO,-87.756075,41.798102,73036,"(41.7981017, -87.7560751)"
7612,ME2015-04564,10/22/2015 10:39:00 AM,10/22/2015 11:05:00 AM,31.0,Male,Other,False,HOMICIDE,HEROIN AND ETHANOL TOXICITY,NaN,NaN,NaN,False,True,5240 NORTH SHERIDAN APT 417,CHICAGO,-87.655620,41.977582,74058,"(41.977582, -87.6556196)"
12656,ME2016-04092,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,4.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,False,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68043,"(41.7477108, -87.5642452)"
12657,ME2016-04093,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,7.0,Female,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,False,False,8112 S. Essex Avenue,CHICAGO,-87.564245,41.747711,68054,"(41.7477108, -87.5642452)"
12660,ME2016-04096,08/23/2016 01:37:00 AM,08/23/2016 06:45:00 AM,56.0,Male,Black,False,HOMICIDE,THERMAL INJURIES AND CARBON MONOXIDE TOXICITY,NaN,NaN,NaN,False,False,8114 S. Essex Avenue,CHICAGO,-87.564246,41.747673,67699,"(41.7476732, -87.5642456)"
13050,ME2016-04490,09/16/2016 02:45:00 AM,09/16/2016 03:34:00 AM,59.0,Male,White,True,HOMICIDE,CARBON MONOXIDE TOXICITY,GARAGE FIRE,NaN,NaN,False,False,2151 W 21st Street,CHICAGO,-87.680361,41.853700,65250,"(41.8536999, -87.6803607)"

### Okay, nope, we were wrong.

Those were almost **all from fires**. Apparently homicide is not the best place to go looking for toxicity. What's the most popular manner of death for primary causes involving toxicity?

- *Tip: Remember that `['colname']` is the same as `.colname`. You can't do `.col with spaces` so you'll need to do `['col with spaces']` a lot in this dataset
- *Tip: Or I guess if you really wanted to, you could rename your columns to have spaces in them (IF YOU DO THIS DON'T DO IT IN EXCEL BECAUSE IT WILL PROBABLY BREAK YOUR CSV.)*

In [242]:
mod = df[df['Manner of Death']]

ValueError: Must pass DataFrame with boolean values only

In [238]:
mod[mod['Primary Cause'].str.contains('.*TOXICITY*.', na=False)]

KeyError: 'Primary Cause'

### Okay, toxicity deaths (overdoses) are mostly accidents. Let's look at the first 30 accidental deaths involving toxicity.

- *Tip: Remember your parentheses!*

In [243]:
#not sure what happened above

## Wow, that's a lot of drug overdoses. What's more popular for overdosing: heroin, fentanyl, cocaine, or ethanol?

You can count something like "COMBINED ETHANOL, NORDIAZEPAM, AND FENTANYL TOXICITY" under both ethanol and fentanyl.

- *Tip: Search for them individually*

# Cleaning up Primary Cause

Let's stop investigating for a second and maybe clean up this "Primary Cause" column.

## What are the most common Primary Cause of death? Include `NaN` values

- *Tip: There is an option that keeps `NaN` values when counting things in a column.*

## That was horrible looking. I don't want to read through that - how many `NaN` causes of death are there?

- *Tip: You can use `isnull()` to see if it's missing data, but how do you count the results?*

## Remove all rows where the primary cause of death has not been filled out.

- *Tip: confirm that you have 22510 rows when you're done*

# Cardiovascular disease

Cardiovascular disease (heart disease) is the number one or number two killer in America.

### Filter for only rows where cardiovascular disease was a primary cause

- *Tip: I hope you know how to deal with the `NaN` error message by now!*

### What are the different types?

### Replace all of those with a nice simple 'CARDIOVASCULAR DISEASE'

- *Tip: you can use `.replace` or `.str.replace`, but they each involve different things! I suggest `.replace`, it looks a little cleaner in this situation*
- *Tip: for `.replace`, you need to give it more options than usual*
- *Tip: for `.str.replace`, it won't automatically save back into the column, you need to do that yourself*

### Check the top 5 primary causes. Cardiovascular disease should be first with about 28.4%

We could also clean up gunshots, but... let's just move on.

# The Opioid Epidemic

America has a [big problem with fentanyl](https://www.theatlantic.com/health/archive/2018/05/americas-opioid-crisis-is-now-a-fentanyl-crisis/559445/) and other opioids.

## Find all of the rows where fentanyl was part of the primary cause of death

We don't need `na=False` any more because we *dropped the rows without primary causes*.

## Fentanyl and race

In the late 80's and 90's, the [crack cocaine epidemic](https://en.wikipedia.org/wiki/Crack_epidemic) swept through inner cities in the US. It was treated primarily as a crime problem, while many people say fentanyl and heroin overdoses are being treated as a medical problem due to the racial differences - the crack epidemic mainly affected Black communities, while fentanyl seems to be a problem for everyone.

### How does the racial breakdown of fentanyl deaths compare to the racial breakdown of other causes of death? How about compared to causes of accidental death?

### Now compare it to homicides

### Now compare it to suicide

## These differences seems kind of crazy

Let's look at all of these at once: I want a breakdown of the most common manners of death for **men**, based on race.

Percentages, please, not raw numbers.

You can look at women, too, although I think the numbers are more surprising for men.

## Back to drugs: what is the most popular opioid-related primary cause of death that does NOT involve fentanyl?

- *Tip: Pay attention to your column names! There's one that might tell you if something is opioid-related...*
- *Tip: Usually you can use `not` or `!` to means "not", but for pandas and `.isin` or `.str.contains` you need to use `~`*
- *Tip: For "and" in pandas you'll need to use `&`, and make sure all of your clauses have parens around them, e.g. `df[(df.col1 = 'A') & (df.col2 = 'B')]`.*

# How do heroin and fentanyl deaths compare?

## Count the number of deaths involving heroin, the number of deaths involving fentanyl, and the number of deaths involving both.

- *Tip: This will take 3 different statements*
- *Tip: You should get `813` that include both*

## That's weird.

I heard fentanyl really surpassed heroin in the past few years. Let's see how this 

### Pull the year out and store it in a new column called `year`

If you run `df['Date of Incident'].str.extract("(\d\d\d\d)", expand=False)`, it will pull out the year of each incident. **Store this in a new column called `year`.**

(It's regular expression stuff. `\d\d\d\d` means "four numbers in a row", and `()` + `.str.extract` means "pull it out".)

### What is the datatype of the new `year` column?

## Convert this new column to an integer and save it back on top of itself

- *Tip: This uses is your friend `.astype`*
- *Tip: Make sure to save it back on top of itself!*

## Confirm the column is a number

## Plot the number of opioid deaths by year

If you'd like to make it look nicer, do some sorting and get rid of 2018.

- *Tip: Think of it in a few steps. First, filter for opioid deaths. Then get the number of deaths for each year. Then plot it.*
- *Tip: What's up with 2018? Why's it look so weird? Can you get rid of it? Remember to use lots of parens!*
- *Tip: Make sure the earliest year is on the left. You might need to sort by something other than values.*

## Plot the number of fentanyl deaths by year, and the number of heroin deaths by year

- *Tip: You'll want to look up how to use `ylim` - it will let you set each graphic to use the same scale. This should be separate graphics.*
- *Tip: Pay attention to the numbers on your axes. `sort_index()` will be your friend.*
- *Tip: You should probably get rid of 2018*

## How does this compare to gun deaths?

## But hey: numbers can lie pretty easily!

The numbers are just so low in 2014 and much higher in 2017. What's going on there?

Well, maybe **there just isn't as much data from the earlier years**. Plot how many entries there are for each year.

And we don't know the best way to fix that up yet, so instead I'm going to give you a present.

# Is the true lesson here, don't move to Cook County, Illinois?

Cook County is basically Chicago. It's probably just certain areas that are trouble, right? Let's investigate that without even having a clue how mapping works.

## Fun bonus: Making cheating maps

### Make a new dataframe of every death in the actual city of Chicago

### Confirm this new dataframe has 13,627 rows

### Use lat and long in the worst way possible to make a map

Use `longitude` and `latitude` and `plot` to make a rough map of the city. Chicago [looks like this](https://en.wikipedia.org/wiki/File:DuPage_County_Illinois_Incorporated_and_Unincorporated_areas_Chicago_Highlighted.svg)

- *Tip: Use the `latitude` and `longitude` columns*
- *Tip: You don't want a line graph, of course. Or a bar. What kind is the kind with dots on it?*
- *Tip: Use something like like `figsize=(10,5)` to specify the height and width of the map (but, you know, with better numbers that make it look like chicago)*

## Now let's find out where to live

Make a map of every non-homicide death in Chicago, then plot the homicides on top of it.

Use the `ax=df.plot` trick from the beer cans assignment to plot all of the rows representing homicides vs non-homicides. You can use `color='red'` to make one of them red, and `alpha=0.05` to make each mark very transparent to allow them to layer on top of each other.

## Never tell anyone I let you do that.

But you want to see something actually completely legitimately insane?

**Chicago is one of the most segregated cities in America.** If you'd like to see this for yourself, make a map of `Race`. Plot black vs white in a way similar to what we did above.

Yup.